// <auto-generated />
namespace SG_ParkEvent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BO_DAL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BO_DAL));
        
        string IMigrationMetadata.Id
        {
            get { return "201805150935085_BO_DAL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
