// <auto-generated />
namespace SG_ParkEvent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ajoutchampimager : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ajoutchampimager));
        
        string IMigrationMetadata.Id
        {
            get { return "201805171209136_ajout champ imager"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
